jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
    demands: LATEST_DOTNET_VERSION -equals 3.1
    workspace:
      clean: all
  variables:
  - name: BuildConfiguration
    value: release
  - group: BUILD Management Resources
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloudProjectKey: SkillsFundingAgency_das-download-service

  - task: DotNetCoreCLI@2
    displayName: 'Publish Website'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.DownloadService.Web/SFA.DAS.DownloadService.Web.csproj'
      arguments: '--configuration release --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'
      modifyOutputPath: true
      zipAfterPublish: true

  - task: DotNetCoreCLI@2
    displayName: 'Publish API'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.DownloadService.Api/SFA.DAS.DownloadService.Api.csproj'
      arguments: '--configuration release --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'
      modifyOutputPath: true
      zipAfterPublish: true

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'
